[2025-03-23 22:55:44,614] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:55:45,719] INFO Retrieving saving goal with ID: 1 - call_trace=/app/app.py L107 
[2025-03-23 22:55:45,723] INFO Saving goal with ID 1 found - call_trace=/app/app.py L120 
[2025-03-23 22:55:46,574] INFO 172.22.0.1 - - [23/Mar/2025 22:55:46] "GET /goals/{goal_id}?goal_id=1 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:56:00,415] INFO  * Detected change in '/app/app.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:56:00,553] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:56:01,326] INFO Retrieving saving goal with ID: 1 - call_trace=/app/app.py L107 
[2025-03-23 22:56:01,332] INFO Saving goal with ID 1 found - call_trace=/app/app.py L120 
[2025-03-23 22:56:02,089] INFO 172.22.0.1 - - [23/Mar/2025 22:56:02] "GET /goals/{goal_id}?goal_id=1 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:58:54,264] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:58:54,397] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:00:38,612] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:00:38,774] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:01:54,934] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:01:55,151] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:06:47,485] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:06:47,639] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:07:14,508] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:07:14,664] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:11,535] INFO [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5000
 * Running on http://172.22.0.2:5000 - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:11,536] INFO [33mPress CTRL+C to quit[0m - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:11,536] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,082] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,105] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,109] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,111] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,215] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:20,217] INFO 172.22.0.1 - - [23/Mar/2025 23:08:20] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:38,393] INFO Adding saving goal with name: 'Pretty dress' - call_trace=/app/app.py L39  
[2025-03-23 23:08:38,531] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:38,730] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:08:44,577] INFO Adding saving goal with name: 'Pretty dress' - call_trace=/app/app.py L39  
[2025-03-23 23:08:52,902] ERROR $CURRENCYENUMSCHEMA.USDBRL=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 23:08:52,911] WARNING Error adding saving goal 'Pretty dress', Saving goal with the same name already exists in the database. - call_trace=/app/app.py L58  
[2025-03-23 23:08:52,912] INFO 172.22.0.1 - - [23/Mar/2025 23:08:52] "[31m[1mPOST /goals HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:09:23,009] INFO Retrieving all saving goals - call_trace=/app/app.py L77  
[2025-03-23 23:09:23,014] INFO 172.22.0.1 - - [23/Mar/2025 23:09:23] "GET /goals HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:09:55,836] INFO Adding saving goal with name: 'Pretty dress2' - call_trace=/app/app.py L39  
[2025-03-23 23:09:58,946] ERROR $CURRENCYENUMSCHEMA.USDBRL=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 23:09:58,950] WARNING Error adding saving goal 'Pretty dress2', Saving goal with the same name already exists in the database. - call_trace=/app/app.py L58  
[2025-03-23 23:09:58,950] INFO 172.22.0.1 - - [23/Mar/2025 23:09:58] "[31m[1mPOST /goals HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:12:21,707] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:12:21,841] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:12:27,476] INFO Adding saving goal with name: 'Pretty dress3' - call_trace=/app/app.py L39  
[2025-03-23 23:12:35,622] ERROR $CURRENCYENUMSCHEMA.USDBRL=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 23:12:35,630] WARNING Error adding saving goal 'Pretty dress3', Saving goal with the same name already exists in the database. - call_trace=/app/app.py L58  
[2025-03-23 23:12:35,632] INFO 172.22.0.1 - - [23/Mar/2025 23:12:35] "[31m[1mPOST /goals HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:16:01,593] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:16:01,722] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:17:13,818] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:17:13,950] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:17:52,793] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:17:52,940] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:17:58,380] INFO Adding saving goal with name: 'Pretty dress4' - call_trace=/app/app.py L39  
[2025-03-23 23:18:05,965] ERROR $CURRENCYENUMSCHEMA.USDBRL=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 23:18:05,975] WARNING Error adding saving goal 'Pretty dress4', Saving goal with the same name already exists in the database. - call_trace=/app/app.py L58  
[2025-03-23 23:18:05,979] INFO 172.22.0.1 - - [23/Mar/2025 23:18:05] "[31m[1mPOST /goals HTTP/1.1[0m" 409 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:19:25,051] INFO  * Detected change in '/app/models/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:19:25,225] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 23:19:33,570] INFO Adding saving goal with name: 'Pretty dress5' - call_trace=/app/app.py L39  
[2025-03-23 23:20:11,202] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
