[2025-03-23 22:11:33,633] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,118] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,142] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,143] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,144] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,287] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:36,290] INFO 172.22.0.1 - - [23/Mar/2025 22:11:36] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:11:54,284] ERROR $CURRENCYENUMSCHEMA.BRLCURRENCYENUMSCHEMA.USD=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 22:11:54,288] INFO 172.22.0.1 - - [23/Mar/2025 22:11:54] "[35m[1mGET /convert-currency?amount=3&from_currency=BRL&to_currency=USD HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:12:33,721] INFO  * Detected change in '/app/app.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:12:33,872] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:12:46,008] ERROR $CURRENCYENUMSCHEMA.BRLCURRENCYENUMSCHEMA.USD=X: possibly delisted; no price data found  (period=1d) (Yahoo error = "No data found, symbol may be delisted") - call_trace=/usr/local/lib/python3.12/site-packages/yfinance/scrapers/history.py L247 
[2025-03-23 22:12:46,012] INFO 172.22.0.1 - - [23/Mar/2025 22:12:46] "[35m[1mGET /convert-currency?amount=3&from_currency=BRL&to_currency=USD HTTP/1.1[0m" 500 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:13:25,876] INFO  * Detected change in '/app/app.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:13:26,004] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:13:30,338] INFO 172.22.0.1 - - [23/Mar/2025 22:13:30] "GET /convert-currency?amount=3&from_currency=BRL&to_currency=USD HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:14:00,655] INFO 172.22.0.1 - - [23/Mar/2025 22:14:00] "GET /convert-currency?amount=3&from_currency=USD&to_currency=BRL HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:17:26,081] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:17:26,212] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:44,379] INFO  * Detected change in '/app/app.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:44,533] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,833] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "GET /openapi/swagger HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,859] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "[36mGET /openapi/static/js/swagger-ui-bundle.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,863] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "[36mGET /openapi/static/css/swagger-ui.css HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,864] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "[36mGET /openapi/static/js/swagger-ui-standalone-preset.js HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,954] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "GET /openapi/openapi.json HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:48,962] INFO 172.22.0.1 - - [23/Mar/2025 22:31:48] "[36mGET /openapi/static/images/swagger.svg HTTP/1.1[0m" 304 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:31:54,140] INFO Retrieving all saving goals - call_trace=/app/app.py L74  
[2025-03-23 22:31:54,144] INFO 1 saving goals found - call_trace=/app/app.py L84  
[2025-03-23 22:31:54,144] INFO 172.22.0.1 - - [23/Mar/2025 22:31:54] "GET /goals HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:32:33,591] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:32:33,725] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:32:34,504] INFO Retrieving all saving goals - call_trace=/app/app.py L74  
[2025-03-23 22:32:34,507] INFO 1 saving goals found - call_trace=/app/app.py L84  
[2025-03-23 22:32:34,508] INFO 172.22.0.1 - - [23/Mar/2025 22:32:34] "GET /goals HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:32:55,069] INFO Adding saving goal with name: 'Pretty dress' - call_trace=/app/app.py L36  
[2025-03-23 22:32:55,079] INFO Saving goal added successfully - call_trace=/app/app.py L49  
[2025-03-23 22:32:55,081] INFO 172.22.0.1 - - [23/Mar/2025 22:32:55] "POST /goals HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:33:05,471] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L104 
[2025-03-23 22:33:05,474] INFO Saving goal with ID 2 found - call_trace=/app/app.py L117 
[2025-03-23 22:33:05,474] INFO 172.22.0.1 - - [23/Mar/2025 22:33:05] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:33:55,980] INFO  * Detected change in '/app/app.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:33:56,149] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:36:51,667] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:36:51,802] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:21,668] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:21,828] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:22,619] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:37:22,625] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:37:22,626] INFO 172.22.0.1 - - [23/Mar/2025 22:37:22] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:23,805] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:37:23,806] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:37:23,807] INFO 172.22.0.1 - - [23/Mar/2025 22:37:23] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:37,701] INFO  * Detected change in '/app/schemas/saving_goal.py', reloading - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:37,839] INFO  * Restarting with stat - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:45,171] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:37:45,176] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:37:45,178] INFO 172.22.0.1 - - [23/Mar/2025 22:37:45] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
[2025-03-23 22:37:52,475] INFO Retrieving saving goal with ID: 2 - call_trace=/app/app.py L107 
[2025-03-23 22:37:52,476] INFO Saving goal with ID 2 found - call_trace=/app/app.py L120 
[2025-03-23 22:37:52,477] INFO 172.22.0.1 - - [23/Mar/2025 22:37:52] "GET /goals/{goal_id}?goal_id=2 HTTP/1.1" 200 - - call_trace=/usr/local/lib/python3.12/site-packages/werkzeug/_internal.py L97  
